[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "imdbkit"
version = "1.0.0"
description = "Lightweight IMDb and TMDB metadata library for Python bots"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

authors = [
    {name = "DeveloperBoy-A"}
]

dependencies = [
    "rapidfuzz>=3.0.0",
]


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
include = ["imdbkit*"]
